name: 'firebase deploy'
description: 'firebase deploy'

inputs:
  project_id:
    description: 'project_id'
    required: true
  firebase_token:
    description: 'Firebase token for deployment'
    required: true
  firebase_json:
    description: 'Firebase json'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Create JSON file from secret
      run: echo "${{ inputs.firebase_json }}" | base64 -d > firebase.json
      shell: bash

    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      shell: bash

    - name: Deploy to Firebase
      run: firebase deploy --token ${{ inputs.firebase_token }} --project ${{ inputs.project_id }}
      shell: bash