name: Deploy to Dev Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: deploy
        uses: ./.github/actions/deploy
        with:
          project_id: quzishare